server:
  port: 8080

spring:
  datasource:
    name: test2
    url: jdbc:mysql://127.0.0.1:3306/ppg
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver



## 该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zzwq.dromitory.entity  # 注意：对应实体类的路径

